export const SUPPORTED_UI_LOCALES = ['zh-CN', 'en-US'] as const;

export type UiLocale = (typeof SUPPORTED_UI_LOCALES)[number];

export const DEFAULT_UI_LOCALE: UiLocale = 'zh-CN';

interface UiTextDictionary {
  [key: string]: string | UiTextDictionary;
}

type UiTextValue = string | UiTextDictionary;

const MESSAGES: Record<UiLocale, UiTextValue> = {
  'zh-CN': {
    common: {
      unknown: '未知',
      unknownPath: '未知路径',
      untitledProject: '未命名项目',
      unknownProject: '未知项目',
      open: '打开',
      openDetail: '打开详情',
      openProject: '打开项目',
      openFolder: '打开目录',
      retry: '重试',
      search: '搜索',
      summary: '概览',
      back: '返回',
      add: '添加',
      remove: '移除',
      enable: '开启',
      disable: '关闭',
      enabled: '已启用',
      disabled: '未启用',
      available: '可用',
      readonly: '只读',
      static: '静态',
      dynamic: '动态',
      direct: '直接',
      viaPreset: '来自技能集',
      none: '无',
      notConfigured: '未配置',
      notAvailable: '不可用',
      saving: '保存中...',
      loading: '加载中...',
      updating: '更新中...',
      deleting: '删除中...',
      opening: '打开中...',
      choosingFolder: '选择目录中...',
      viewAll: '查看全部',
      actions: '项操作',
      matchedProject: '已匹配项目',
      unmatched: '未匹配',
      noMatch: '未匹配',
      scopeGlobal: '全局',
      scopeProject: '项目',
    },
    nav: {
      overview: '总览',
      projects: '项目',
      skills: '技能',
      presets: '技能集',
      config: '配置',
    },
    route: {
      workbench: '总览',
      openingWorkbench: '正在打开界面',
      projectDetail: '项目详情',
      presetDetail: '技能集详情',
      notFound: '页面不存在',
    },
    router: {
      missing: {
        notReady: '{{label}} 页面尚未就绪。',
        autoAppear: '补齐页面实现后，这个模块会自动显示。',
      },
    },
    app: {
      brandTag: '控制台',
      brandNote: '在全局与项目范围内进行精确控制。',
      openNavigation: '打开导航',
      closeNavigation: '关闭导航',
      workspace: '当前页面',
      contextRuntime: '上下文 / 运行时',
      currentSession: '当前会话',
      launchCwd: '启动目录',
      projectMatch: '项目匹配',
      scopeTargets: '范围 / 目标',
      runtime: '运行时',
      unmatchedLaunchDirectory: '未匹配到目录',
      folderPathUnavailable: '目录路径不可用',
      contextAwareWorkbench: '上下文导航',
      targets: '目标：{{targets}}',
      waitingRuntimeStatus: '等待运行时状态…',
      checkingRuntime: '检查运行时中',
      runningRuntime: '运行中 · :{{port}}',
      runningRuntimeFallback: '运行中 · :{{port}}（回退端口）',
      loadLaunchContextFailed: '无法加载启动上下文。',
      openLaunchFolderFailed: '无法打开启动目录。',
      routeDesc: {
        overview: '从当前启动上下文开始，然后进入最有价值的下一步操作。',
        projects: '查看已跟踪项目索引，并进入项目详情控制面板。',
        projectDetail: '在同一页面内调整单个项目并校验解析结果。',
        skills: '查看技能目录、全局状态和作用在哪些项目。',
        presets: '将技能集作为可复用组合单元进行管理。',
        presetDetail: '查看单个技能集及其对相关项目的影响。',
        config: '通过稳定的内联控件调整全局基线配置。',
        fallback: '使用左侧导航返回到当前模块。',
      },
    },
    boot: {
      scopeLabel: '准备页面',
      scopeDescription: '正在解析启动上下文，并选择正确的起始路由。',
      eyebrow: '启动路由',
      title: '正在准备界面',
      copy: '正在匹配启动上下文、加载运行时状态，并将你带到正确的页面。',
    },
    notFound: {
      scopeLabel: '路由不存在',
      scopeDescription: '返回总览，并从已知模块继续。',
      eyebrow: '未知路由',
      title: '这个路径没有映射到任何页面。',
      copy: '请使用左侧索引返回到总览、项目、技能、技能集或配置。',
    },
    overview: {
      loading: '正在加载总览...',
      loadFailed: '无法加载总览上下文。',
      contextPosture: '上下文姿态',
      launchCwd: '启动目录',
      matchedState: '匹配状态',
      primaryScope: '主要范围',
      recommendedNextAction: '推荐下一步',
      recommendedActions: '推荐操作',
      globalOverview: '全局概览',
      recentProjects: '最近项目',
      noTrackedProjects: '当前还没有已跟踪项目。',
      updatedAt: '{{value}}',
    },
    projects: {
      workspaceLabel: '项目索引',
      description: '定位项目、查看其启用摘要，并直接进入详情页。',
      searchPlaceholder: '按项目名、路径、目标或 ID 过滤',
      loading: '正在加载项目...',
      loadFailed: '无法加载项目列表。',
      empty: '还没有已跟踪项目。在项目中启用技能或技能集后就会建立索引。',
      noMatch: '没有项目匹配当前搜索。',
      noTargets: '无目标',
      updatedAt: '更新于 {{value}}',
      skillPresetSummary: '{{skillCount}} 个技能 / {{presetCount}} 个技能集',
      openFailed: '打开项目失败。',
    },
    skills: {
      workspaceLabel: '技能目录',
      title: '技能样本',
      description: '在一个地方查看全局启用状态，并检查作用在哪些项目。',
      searchPlaceholder: '按名称、描述、位置或项目过滤',
      loading: '正在加载技能...',
      loadFailed: '无法加载技能列表。',
      enableFailed: '无法启用技能 {{name}}。',
      disableFailed: '无法停用技能 {{name}}。',
      empty: '当前配置的 `skillsDir` 中还没有可用技能。',
      noMatch: '没有技能匹配当前搜索，请尝试其他关键词。',
      location: '位置',
      updated: '更新时间',
      usage: '使用情况',
      intersection: '作用于',
      directProjects: '直接启用项目',
      noDirectProjects: '当前没有项目直接启用这个技能。',
      noViaPresetProjects: '当前没有项目通过技能集获得这个技能。',
      noDescription: '暂无描述。',
      unknownLocation: '未知位置',
      viaPresetNote: '通过 {{names}}',
    },
    presets: {
      scopeDescription: '技能集目录，包含来源状态与下游引用。',
      scopeErrorDescription: '技能集目录因加载错误暂不可用。',
      workspaceLabel: '技能集目录',
      description: '浏览可复用的技能集组合，并打开详情页查看成员与影响。',
      searchPlaceholder: '按名称、来源或数量过滤',
      loading: '正在加载技能集...',
      loadFailed: '无法加载技能集列表。',
      empty: '当前还没有可用技能集。可通过技能集 API 或 CLI 创建。',
      noMatch: '没有技能集匹配当前搜索。',
      summary: '{{skillCount}} 个技能 / {{projectCount}} 个项目',
    },
    presetDetail: {
      scopeLabel: '技能集',
      scopeDescription: '{{name}} · {{status}} · {{skillCount}} 个技能 / {{projectCount}} 个项目',
      scopeErrorDescription: '技能集详情因加载错误暂不可用。',
      missingName: '路由参数中缺少技能集名称。',
      loading: '正在加载技能集详情...',
      loadFailed: '无法加载技能集详情。',
      workspaceLabel: '技能集详情',
      skillMembership: '技能成员',
      membershipDescription: '直接切换技能成员关系，修改会立即生效。',
      searchPlaceholder: '按名称、描述或路径过滤技能',
      noMatch: '没有技能匹配当前搜索。',
      affectedProjects: '受影响项目',
      affectedProjectsDescription: '这些项目会受到该技能集影响。点击行可打开项目详情。',
      noAffectedProjects: '该技能集当前不会影响任何已跟踪项目。',
      readonlyDeleteBlocked: '技能集 {{name}} 为只读，无法在当前页面移除。',
      updateFailed: '无法更新 {{name}} 的成员关系。',
      deleteFailed: '无法移除技能集。',
      deleted: '已移除技能集 {{name}}。',
      deleteAction: '移除技能集',
      deleteConfirmEmpty: '确认移除技能集 {{name}} 吗？',
      deleteConfirmWithRefs: '技能集 {{name}} 当前影响 {{count}} 个项目。\n\n{{projects}}\n\n确认移除技能集 {{name}} 吗？',
      projectCount: '{{count}} 个项目',
      skillCount: '{{count}} 个技能',
    },
    projectDetail: {
      loading: '正在加载项目详情...',
      missingId: '路由参数中缺少项目 ID。',
      loadFailed: '无法加载项目详情。',
      workspaceLabel: '项目详情',
      targets: '目标：{{targets}} · 更新于 {{updatedAt}}',
      openFailed: '打开项目失败。',
      presets: '技能集',
      presetsDescription: '直接切换项目技能集，修改会立即生效。',
      skills: '技能',
      skillsDescription: '直接技能开关会立即生效；受技能集控制的技能会在这里锁定。',
      searchPlaceholder: '过滤技能',
      resolvedDescription: '这里显示生效技能及其来源标签。每次切换后都会刷新。',
      noEnabledPresets: '该项目当前没有启用任何技能集。',
      allPresetsEnabled: '所有已知技能集都已经启用。',
      noEnabledSkillMatch: '没有已启用技能匹配当前搜索。',
      noAvailableSkillMatch: '没有可用技能匹配当前搜索。',
      noResolvedSkills: '该项目当前没有生效技能。',
      controlledByPreset: '由技能集 {{names}} 控制。',
      fromPreset: '来自 {{names}}',
      updatePresetFailed: '无法更新技能集 {{name}}。',
      updateSkillFailed: '无法更新技能 {{name}}。',
      sourceReadonlySuffix: ' · 只读',
    },
    config: {
      loading: '正在加载全局配置基线...',
      loadFailed: '无法加载配置基线。',
      updateFailed: '无法更新配置。',
      workspaceLabel: '全局基线',
      activeSkillsDir: '当前 skillsDir',
      defaultTargets: '默认目标',
      noDefaultTarget: '没有默认目标。',
      supportedTargets: '支持 {{count}} 个目标。',
      manualEntry: '当前主机不支持目录选择器，使用手动路径输入。',
      pickerAvailable: '当前主机支持目录选择器。',
      workspaceConfig: '当前配置',
      chooseFolder: '选择目录',
      copyPath: '复制路径',
      folderPickerPrompt: '选择 skills 目录',
      folderPickerFailed: '目录选择器执行失败。',
      folderPickerFailedHint: '请改为手动输入目录路径，或检查当前宿主是否允许打开系统目录选择器。',
      pickerUnavailableHint: '如果当前主机不支持目录选择器，请手动粘贴路径并保存。',
      saveConfig: '保存配置',
      storagePaths: '存储路径',
      storagePathsDescription: '当前环境使用的底层文件。',
      pathRequired: '路径不能为空。',
      updated: '全局配置已更新。',
      copied: '已复制 skillsDir 到剪贴板。',
      clipboardUnavailable: '当前浏览器无法使用剪贴板。',
      folderPickerUnavailable: '目录选择器不可用，请手动输入路径。',
      folderPickerHostUnavailable: '当前主机不可使用目录选择器，请手动输入路径。',
      folderSelected: '目录已选中，保存后会应用该路径。',
      notAvailable: '不可用',
    },
    server: {
      unknownApiRoute: '未知 API 路由：{{pathname}}。',
      unknownApiRouteHint: '请使用 `/api/*` 下的已记录路由。',
      unsupportedUiMethod: 'UI 路由不支持该方法：{{method}}。',
      unsupportedUiMethodHint: '加载 Web UI 页面或静态资源时请使用 GET。',
      jsonTooLarge: 'JSON 请求体超过 1MB 限制。',
      jsonTooLargeHint: '请减小请求体后重试。',
      invalidJsonBody: '请求体必须是合法 JSON。',
      invalidJsonBodyHint: '请提供语法正确的 JSON 请求体。',
      unknownFailure: '未知错误。',
      missingAssets: '无法定位 Web UI 静态资源。',
      missingAssetsHint: '请先运行 `pnpm run build:web` 或 `pnpm run build` 生成 Web UI 产物。',
      invalidAssetPath: '无效的静态资源路径。',
      invalidAssetPathHint: '只能请求 Web UI 包内的静态资源。',
      missingAsset: '缺少 Web UI 资源：{{path}}。',
      missingAssetHint: '请重新构建，确保静态资源已生成。',
      upstream: {
        configFieldRequired: '至少需要提供一个配置字段。',
        configFieldRequiredHint: '请提供 `skillsDir` 和/或 `defaultTargets`。',
        skillsDirMissing: 'skillsDir 指向的目录不存在：{{path}}。',
        skillsDirMissingHint: '请先创建该目录，再更新 `skillsDir`。',
        skillsDirNotDirectory: 'skillsDir 指向的路径不是目录：{{path}}。',
        skillsDirNotDirectoryHint: '请为 `skillsDir` 选择一个已存在的目录。',
        unsupportedTarget: '不支持目标 "{{target}}"。',
        unsupportedTargetHint: '请使用以下目标之一：{{targets}}',
        skillNameRequired: '至少需要一个技能名称。',
        skillNameRequiredHint: '请至少提供一个技能名称。',
        presetNameRequired: '至少需要一个技能集名称。',
        presetNameRequiredHint: '请至少提供一个技能集名称。',
        presetSkillsRequired: '技能集至少需要一个技能。',
        presetSkillsRequiredHint: '请至少保留一个技能名称。',
        enableGlobalTargetRequired: '全局启用操作至少需要一个目标。',
        enableGlobalTargetRequiredHint: '请传入 `--target <target>`，或先在全局状态中建立目标。',
        enableTargetRequired: '启用技能或技能集至少需要一个目标。',
        enableTargetRequiredHint: '请传入 `--target <target>`，或在 `config.json` 中配置 `defaultTargets`。',
        presetDefinitionsMissing: '缺少以下技能集定义：{{names}}。',
        presetDefinitionsMissingHint: '请重新创建这些技能集，或在当前范围内运行 `skm preset off {{names}}`。',
        presetReadonly: '技能集 {{name}} 是动态作用域技能集，无法修改。',
        presetReadonlyHint:
          '如需修改，请重命名或移除对应作用域目录，或在 `presets.yaml` 中创建其他静态技能集名。',
        presetNotFound: '找不到技能集 {{name}}。',
        presetNotFoundHint: '请先查看 `skm preset list` 中的可用技能集。',
        presetNameConflict: '技能集名 {{name}} 同时被静态技能集和动态作用域技能集占用。',
        presetNameConflictHint: '请重命名 `presets.yaml` 中的技能集，或重命名对应作用域目录。',
        presetUnknownSkills: '技能集引用了未知技能：{{names}}。',
        presetUnknownSkillsHint: '请运行 `skm skill list`，并只在技能集定义中使用存在的技能名。',
        configuredSkillsDir: '当前 skillsDir：{{path}}。',
        skillNotFound: '找不到技能 {{name}}。',
        skillNotFoundHint: '请检查当前 `skillsDir` 中是否存在该技能。',
      },
    },
    facade: {
      viewGlobalConfig: '查看全局配置',
      listPresets: '列出技能集',
      listSkills: '列出技能',
      inspectCurrentConfig: '检查当前配置',
      setSkillsDirectory: '设置技能目录',
      createPreset: '创建技能集',
      updatePreset: '更新技能集',
      doctorProject: '诊断项目',
      syncProject: '同步项目',
      openProjectDirectory: '打开项目目录',
      projectScopeFirst: '优先处理项目范围',
      projectScopeDescription: '{{name}} 是本次会话的当前项目。',
      globalScopeFirst: '优先处理全局范围',
      globalScopeDescription: '启动路径没有匹配到已跟踪项目，因此从总览和全局状态开始治理。',
      actionAdjustMatchedProject: '调整匹配项目',
      actionAdjustMatchedProjectDesc: '直接进入当前项目详情，调整技能集或直接技能。',
      actionReviewOtherProjects: '查看全部项目',
      actionReviewOtherProjectsDesc: '在进行更大范围治理前，先比较其他已跟踪项目。',
      actionInspectGlobalSkills: '查看全局技能',
      actionInspectGlobalSkillsDesc: '检查技能目录中的全局启用状态和作用在哪些项目。',
      actionReviewTrackedProjects: '查看已跟踪项目',
      actionReviewTrackedProjectsDesc: '先从项目索引理解当前环境中的启用情况。',
      actionGovernPresets: '治理技能集',
      actionGovernPresetsDesc: '在修改单个项目之前先检查可复用技能集组合。',
      actionCheckGlobalBaseline: '检查全局基线',
      actionCheckGlobalBaselineDesc: '查看整个环境的技能目录和默认目标设置。',
      relationshipHeading: '影响链',
      relationshipGlobalPresetsActive: '{{count}} 个全局技能集正在先于项目级覆盖塑造共享默认值。',
      relationshipGlobalPresetsEmpty: '当前没有全局技能集在塑造共享默认值。',
      relationshipProjects: '{{projects}} 个已跟踪项目当前包含 {{count}} 个直接技能分配。',
      relationshipRegistry: '当前有 {{presetCount}} 个技能集定义可用，且有 {{skillCount}} 个技能已在全局启用。',
      configPayloadMustBeObject: '配置更新请求必须是对象。',
      configPayloadHint: '请发送类似 `{ "skillsDir": "...", "defaultTargets": [".agents"] }` 的 JSON。',
      skillsDirMustBeNonEmpty: 'skillsDir 必须是非空字符串。',
      skillsDirHint: '请填写一个已存在的 `skillsDir` 目录路径。',
      skillsDirField: '请填写已存在的目录路径。',
      defaultTargetsMustBeArray: 'defaultTargets 必须是字符串数组。',
      defaultTargetsHint: '请使用以下一个或多个目标：{{targets}}',
      projectNotFound: '项目 {{projectId}} 不存在于项目索引中。',
      projectNotFoundHint: '请先调用 `GET /api/projects` 获取返回的 `projectId`。',
      projectStateMissing: '项目 {{projectPath}} 缺少状态文件。',
      projectStateMissingHint: '请在该项目重新启用一个技能或技能集，以重建 `.skm/state.json`。',
      presetNameRequired: '技能集名称不能为空。',
      presetNameHint: '请提供非空的技能集名称。',
      presetReadonly: '这个技能集为只读。',
      enableGlobalSkillPayload: '开启全局技能的请求必须是对象。',
      enableGlobalSkillPayloadHint: '请发送类似 `{ "skillNames": ["brainstorming"], "targets": [".agents"] }` 的 JSON。',
      disableGlobalSkillPayload: '关闭全局技能的请求必须是对象。',
      disableGlobalSkillPayloadHint: '请发送类似 `{ "skillNames": ["brainstorming"] }` 的 JSON。',
      enableProjectSkillPayload: '开启技能的请求必须是对象。',
      enableProjectSkillPayloadHint: '请发送类似 `{ "skillNames": ["brainstorming"], "targets": [".agents"] }` 的 JSON。',
      disableProjectSkillPayload: '关闭技能的请求必须是对象。',
      disableProjectSkillPayloadHint: '请发送类似 `{ "skillNames": ["brainstorming"] }` 的 JSON。',
      enablePresetPayload: '开启技能集的请求必须是对象。',
      enablePresetPayloadHint: '请发送类似 `{ "presetNames": ["frontend-basic"], "targets": [".agents"] }` 的 JSON。',
      disablePresetPayload: '关闭技能集的请求必须是对象。',
      disablePresetPayloadHint: '请发送类似 `{ "presetNames": ["frontend-basic"] }` 的 JSON。',
      createPresetPayload: '创建技能集的请求必须是对象。',
      createPresetPayloadHint: '请发送类似 `{ "name": "frontend", "skills": ["brainstorming"] }` 的 JSON。',
      updatePresetPayload: '更新技能集的请求必须是对象。',
      updatePresetPayloadHint: '请发送类似 `{ "skills": ["brainstorming"] }` 的 JSON。',
      presetAlreadyExists: '技能集 {{name}} 已存在。',
      presetAlreadyExistsHint: '请换一个名称，或更新现有技能集。',
      presetReadonlyMutation: '技能集 {{name}} 是动态作用域技能集，无法修改。',
      presetReadonlyMutationHint: '如需变更，请重命名或删除对应 scope 目录，或在 `presets.yaml` 中创建其他静态技能集名。',
      presetNotFound: '技能集 {{name}} 不存在。',
      presetNotFoundHint: '请先使用 `skm preset list` 或 `GET /api/presets` 查看可用技能集。',
      presetSkillsRequired: '技能集技能列表不能为空。',
      presetSkillsRequiredHint: '请至少提供一个技能名。',
      presetUnknownSkills: '技能集引用了未知技能：{{names}}。',
      presetUnknownSkillsHint: '请运行 `skm skill list`，并且只在技能集定义中使用已存在的技能名。',
      presetNameFieldRequired: '技能集名称不能为空。',
      presetNameFieldConflict: '请使用不同的技能集名称。',
      stringArrayMustBe: '{{name}} 必须是字符串数组。',
      stringArrayHint: '请将 `{{name}}` 作为 JSON 字符串数组传入。',
      stringArrayField: '{{name}} 必须是字符串列表。',
      skillsDirMissing: 'skillsDir 指向的目录不存在：{{path}}。',
      skillsDirNotDirectory: 'skillsDir 不是目录：{{path}}。',
      skillsDirInvalidHint: '请填写一个存在且为目录的路径。',
      directLabel: '直接',
      viaPresetLabel: '来自技能集：{{name}}',
    },
    quickOpen: {
      openedInCode: '已在 VS Code 中打开项目。',
      openedWithSystem: '已用系统默认处理程序打开项目。',
      failed: '无法打开项目。code：{{codeError}}；default：{{defaultError}}',
    },
    time: {
      unknown: '未知',
      justNow: '刚刚',
      underMinuteFuture: '不到 1 分钟后',
      minuteAgo: '{{count}} 分钟前',
      minuteIn: '{{count}} 分钟后',
      hourAgo: '{{count}} 小时前',
      hourIn: '{{count}} 小时后',
      yesterday: '昨天',
      tomorrow: '明天',
      dayAgo: '{{count}} 天前',
      dayIn: '{{count}} 天后',
    },
  },
  'en-US': {
    common: {
      unknown: 'Unknown',
      unknownPath: 'Unknown path',
      untitledProject: 'Untitled project',
      unknownProject: 'Unknown project',
      open: 'Open',
      openDetail: 'Open Detail',
      openProject: 'Open Project',
      openFolder: 'Open Folder',
      retry: 'Retry',
      search: 'Search',
      summary: 'Summary',
      back: 'Back',
      add: 'Add',
      remove: 'Remove',
      enable: 'On',
      disable: 'Off',
      enabled: 'Enabled',
      disabled: 'Disabled',
      available: 'Available',
      readonly: 'Readonly',
      static: 'Static',
      dynamic: 'Dynamic',
      direct: 'Direct',
      viaPreset: 'Via Preset',
      none: 'None',
      notConfigured: 'Not configured',
      notAvailable: 'Not available',
      saving: 'Saving...',
      loading: 'Loading...',
      updating: 'Updating...',
      deleting: 'Deleting...',
      opening: 'Opening...',
      choosingFolder: 'Choosing Folder...',
      viewAll: 'View All',
      actions: 'actions',
      matchedProject: 'Matched Project',
      unmatched: 'Unmatched',
      noMatch: 'No Match',
      scopeGlobal: 'Global',
      scopeProject: 'Project',
    },
    nav: {
      overview: 'Overview',
      projects: 'Projects',
      skills: 'Skills',
      presets: 'Presets',
      config: 'Config',
    },
    route: {
      workbench: 'Overview',
      openingWorkbench: 'Opening Interface',
      projectDetail: 'Project Detail',
      presetDetail: 'Preset Detail',
      notFound: 'Not Found',
    },
    router: {
      missing: {
        notReady: '{{label}} is not ready yet.',
        autoAppear: 'This module will appear automatically after its page implementation is added.',
      },
    },
    app: {
      brandTag: 'Console',
      brandNote: 'Precise control across global and project scopes.',
      openNavigation: 'Open navigation',
      closeNavigation: 'Close navigation',
      workspace: 'Current Page',
      contextRuntime: 'Context / Runtime',
      currentSession: 'Current Session',
      launchCwd: 'Launch CWD',
      projectMatch: 'Project Match',
      scopeTargets: 'Scope / Targets',
      runtime: 'Runtime',
      unmatchedLaunchDirectory: 'No matching directory',
      folderPathUnavailable: 'Folder path unavailable',
      contextAwareWorkbench: 'Context-aware navigation',
      targets: 'Targets: {{targets}}',
      waitingRuntimeStatus: 'Waiting for runtime status…',
      checkingRuntime: 'Checking runtime',
      runningRuntime: 'Running · :{{port}}',
      runningRuntimeFallback: 'Running · :{{port}} (fallback)',
      loadLaunchContextFailed: 'Unable to load launch context.',
      openLaunchFolderFailed: 'Unable to open launch folder.',
      routeDesc: {
        overview: 'Start from launch context, then move into the most useful action.',
        projects: 'Browse tracked projects as index rows and jump into project detail control surfaces.',
        projectDetail: 'Adjust one project and verify its resolved outcomes on the same page.',
        skills: 'Review the skill directory, global status, and project intersections.',
        presets: 'Manage presets as reusable composition units.',
        presetDetail: 'Inspect one preset and its impact on related projects.',
        config: 'Tune global baseline configuration with calm inline controls.',
        fallback: 'Use the left navigation to return to the active module.',
      },
    },
    boot: {
      scopeLabel: 'Preparing page',
      scopeDescription: 'Resolving launch context and choosing the correct starting route.',
      eyebrow: 'Boot Routing',
      title: 'Preparing interface',
      copy: 'Matching launch context, loading runtime status, and taking you to the right page.',
    },
    notFound: {
      scopeLabel: 'Route not found',
      scopeDescription: 'Return to overview and continue from a known module.',
      eyebrow: 'Unknown Route',
      title: 'This path does not map to any page.',
      copy: 'Use the left index to return to Overview, Projects, Skills, Presets, or Config.',
    },
    overview: {
      loading: 'Loading overview...',
      loadFailed: 'Failed to load overview context.',
      contextPosture: 'Context Posture',
      launchCwd: 'Launch CWD',
      matchedState: 'Matched State',
      primaryScope: 'Primary Scope',
      recommendedNextAction: 'Recommended Next Action',
      recommendedActions: 'Recommended Actions',
      globalOverview: 'Global Overview',
      recentProjects: 'Recent Projects',
      noTrackedProjects: 'No tracked projects available yet.',
      updatedAt: '{{value}}',
    },
    projects: {
      workspaceLabel: 'Projects Index',
      description: 'Locate a project, inspect its enabled summary, and jump straight into the detail page.',
      searchPlaceholder: 'Filter by project name, path, target, or id',
      loading: 'Loading projects...',
      loadFailed: 'Failed to load projects.',
      empty: 'No tracked project yet. Enable a skill or preset in a project to start building the index.',
      noMatch: 'No project matches this search query.',
      noTargets: 'No targets',
      updatedAt: 'Updated {{value}}',
      skillPresetSummary: '{{skillCount}} skills / {{presetCount}} presets',
      openFailed: 'Open Project failed.',
    },
    skills: {
      workspaceLabel: 'Skills Directory',
      title: 'Skill Samples',
      description: 'Review global activation and inspect project intersections in one place.',
      searchPlaceholder: 'Filter by name, description, location, or project',
      loading: 'Loading skills...',
      loadFailed: 'Failed to load skills.',
      enableFailed: 'Failed to enable skill {{name}}.',
      disableFailed: 'Failed to disable skill {{name}}.',
      empty: 'No skills are available in the configured `skillsDir` yet.',
      noMatch: 'No skill matches this search. Try another keyword.',
      location: 'Location',
      updated: 'Updated',
      usage: 'Usage',
      intersection: 'Intersection',
      directProjects: 'Direct Projects',
      noDirectProjects: 'No projects currently enable this skill directly.',
      noViaPresetProjects: 'No project receives this skill through presets.',
      noDescription: 'No description available.',
      unknownLocation: 'Unknown location',
      viaPresetNote: 'via {{names}}',
    },
    presets: {
      scopeDescription: 'Preset directory with scoped source state and downstream references.',
      scopeErrorDescription: 'Preset directory is unavailable due to loading error.',
      workspaceLabel: 'Preset Directory',
      description: 'Browse reusable preset bundles, then open the detail page for membership and impact.',
      searchPlaceholder: 'Filter by name, source, or count',
      loading: 'Loading presets...',
      loadFailed: 'Failed to load presets.',
      empty: 'No presets are available yet. Create one with the preset API or CLI.',
      noMatch: 'No preset matches this search query.',
      summary: '{{skillCount}} skills / {{projectCount}} projects',
    },
    presetDetail: {
      scopeLabel: 'Preset',
      scopeDescription: '{{name}} · {{status}} · {{skillCount}} skills / {{projectCount}} projects',
      scopeErrorDescription: 'Preset detail is unavailable due to loading error.',
      missingName: 'Preset name is missing from route params.',
      loading: 'Loading preset detail...',
      loadFailed: 'Failed to load preset detail.',
      workspaceLabel: 'Preset Detail',
      skillMembership: 'Skill Membership',
      membershipDescription: 'Toggle skill membership directly. Updates apply immediately.',
      searchPlaceholder: 'Filter skills by name, description, or path',
      noMatch: 'No skill matches this query.',
      affectedProjects: 'Affected Projects',
      affectedProjectsDescription: 'Projects influenced by this preset. Select a row to open project detail.',
      noAffectedProjects: 'This preset does not currently affect any tracked project.',
      readonlyDeleteBlocked: 'Preset {{name}} is readonly and cannot be removed from this page.',
      updateFailed: 'Failed to update membership for {{name}}.',
      deleteFailed: 'Failed to remove preset.',
      deleted: 'Removed preset {{name}}.',
      deleteAction: 'Remove Preset',
      deleteConfirmEmpty: 'Remove preset {{name}}?',
      deleteConfirmWithRefs: 'Preset {{name}} currently affects {{count}} project(s).\n\n{{projects}}\n\nRemove preset {{name}}?',
      projectCount: '{{count}} projects',
      skillCount: '{{count}} skills',
    },
    projectDetail: {
      loading: 'Loading project detail...',
      missingId: 'Project id is missing from route params.',
      loadFailed: 'Failed to load project detail.',
      workspaceLabel: 'Project Detail',
      targets: 'Targets: {{targets}} · Updated {{updatedAt}}',
      openFailed: 'Open Project failed.',
      presets: 'Presets',
      presetsDescription: 'Toggle project presets directly. Changes are applied immediately.',
      skills: 'Skills',
      skillsDescription: 'Direct skill toggles apply immediately. Skills controlled by presets remain locked here.',
      searchPlaceholder: 'Filter skills',
      resolvedDescription: 'Effective skill list with source labels. This panel refreshes after every toggle.',
      noEnabledPresets: 'No preset is enabled in this project.',
      allPresetsEnabled: 'All known presets are already enabled.',
      noEnabledSkillMatch: 'No enabled skill matches this query.',
      noAvailableSkillMatch: 'No available skill matches this query.',
      noResolvedSkills: 'No effective skill is active in this project.',
      controlledByPreset: 'Controlled by preset {{names}}.',
      fromPreset: 'From {{names}}',
      updatePresetFailed: 'Failed to update preset {{name}}.',
      updateSkillFailed: 'Failed to update skill {{name}}.',
      sourceReadonlySuffix: ' · readonly',
    },
    config: {
      loading: 'Loading global config baseline...',
      loadFailed: 'Failed to load config baseline.',
      updateFailed: 'Failed to update config.',
      workspaceLabel: 'Global Baseline',
      activeSkillsDir: 'Active skillsDir',
      defaultTargets: 'Default Targets',
      noDefaultTarget: 'No default target.',
      supportedTargets: '{{count}} supported targets.',
      manualEntry: 'Folder picker unavailable; manual path entry is active.',
      pickerAvailable: 'Folder picker is available.',
      workspaceConfig: 'Active Config',
      chooseFolder: 'Choose Folder',
      copyPath: 'Copy Path',
      folderPickerPrompt: 'Choose a skills directory',
      folderPickerFailed: 'Folder picker failed.',
      folderPickerFailedHint: 'Paste the path manually or check whether this host allows the native folder picker.',
      pickerUnavailableHint: 'If folder picker is unavailable in this host, paste the path manually and save.',
      saveConfig: 'Save Config',
      storagePaths: 'Storage Paths',
      storagePathsDescription: 'Underlying files used by this setup.',
      pathRequired: 'Path is required.',
      updated: 'Global config updated.',
      copied: 'skillsDir copied to clipboard.',
      clipboardUnavailable: 'Clipboard is unavailable in this browser.',
      folderPickerUnavailable: 'Folder picker is not available. Enter the path manually.',
      folderPickerHostUnavailable: 'Folder picker is unavailable in this host. Enter the path manually.',
      folderSelected: 'Folder selected. Save to apply this path.',
      notAvailable: 'Not available',
    },
    server: {
      unknownApiRoute: 'Unknown API route: {{pathname}}.',
      unknownApiRouteHint: 'Use documented routes under `/api/*`.',
      unsupportedUiMethod: 'Unsupported method for UI route: {{method}}.',
      unsupportedUiMethodHint: 'Use GET when loading Web UI pages or assets.',
      jsonTooLarge: 'JSON body exceeds 1MB limit.',
      jsonTooLargeHint: 'Reduce payload size and retry.',
      invalidJsonBody: 'Request body must be valid JSON.',
      invalidJsonBodyHint: 'Provide a syntactically valid JSON payload.',
      unknownFailure: 'Unknown failure.',
      missingAssets: 'Unable to locate Web UI assets.',
      missingAssetsHint: 'Run `pnpm run build:web` or `pnpm run build` to generate the Web UI assets first.',
      invalidAssetPath: 'Invalid asset path.',
      invalidAssetPathHint: 'Request assets inside the Web UI bundle only.',
      missingAsset: 'Missing Web UI asset: {{path}}.',
      missingAssetHint: 'Rebuild the package so static assets are available.',
      upstream: {
        configFieldRequired: 'At least one config field is required.',
        configFieldRequiredHint: 'Provide `skillsDir` and/or `defaultTargets`.',
        skillsDirMissing: 'skillsDir does not exist: {{path}}.',
        skillsDirMissingHint: 'Create the directory first, then update `skillsDir` again.',
        skillsDirNotDirectory: 'skillsDir is not a directory: {{path}}.',
        skillsDirNotDirectoryHint: 'Choose an existing directory for `skillsDir`.',
        unsupportedTarget: 'Unsupported target "{{target}}".',
        unsupportedTargetHint: 'Use one of: {{targets}}',
        skillNameRequired: 'At least one skill name is required.',
        skillNameRequiredHint: 'Provide at least one skill name.',
        presetNameRequired: 'At least one preset name is required.',
        presetNameRequiredHint: 'Provide at least one preset name.',
        presetSkillsRequired: 'Preset skills cannot be empty.',
        presetSkillsRequiredHint: 'Keep at least one skill name in the preset.',
        enableGlobalTargetRequired: 'At least one target is required for global enable operations.',
        enableGlobalTargetRequiredHint:
          'Pass `--target <target>` or establish targets in the global state first.',
        enableTargetRequired: 'At least one target is required to enable skills or presets.',
        enableTargetRequiredHint: 'Pass `--target <target>` or configure `defaultTargets` in `config.json`.',
        presetDefinitionsMissing: 'Preset definitions are missing for {{names}}.',
        presetDefinitionsMissingHint:
          'Recreate the missing presets or run `skm preset off {{names}}` in this scope.',
        presetReadonly: 'Preset {{name}} is a dynamic scope preset and cannot be modified.',
        presetReadonlyHint:
          'Rename or remove the scope directory to change it, or create a different static preset name in `presets.yaml`.',
        presetNotFound: 'Preset {{name}} was not found.',
        presetNotFoundHint: 'Check `skm preset list` to see the available presets.',
        presetNameConflict: 'Preset name {{name}} is defined both statically and as a dynamic scope preset.',
        presetNameConflictHint:
          'Rename the preset in `presets.yaml` or rename the scope directory to remove the ambiguity.',
        presetUnknownSkills: 'Preset references unknown skill(s): {{names}}.',
        presetUnknownSkillsHint: 'Run `skm skill list` and use only existing skill names in preset definitions.',
        configuredSkillsDir: 'Configured skills directory: {{path}}.',
        skillNotFound: 'Skill {{name}} was not found.',
        skillNotFoundHint: 'Check whether the current `skillsDir` contains that skill.',
      },
    },
    facade: {
      viewGlobalConfig: 'View global config',
      listPresets: 'List presets',
      listSkills: 'List skills',
      inspectCurrentConfig: 'Inspect current config',
      setSkillsDirectory: 'Set skills directory',
      createPreset: 'Create preset',
      updatePreset: 'Update preset',
      doctorProject: 'Doctor project',
      syncProject: 'Sync project',
      openProjectDirectory: 'Open project directory',
      projectScopeFirst: 'Project scope first',
      projectScopeDescription: '{{name}} is the active project for this session.',
      globalScopeFirst: 'Global scope first',
      globalScopeDescription: 'No tracked project matches the launch path, so governance starts from overview and global state.',
      actionAdjustMatchedProject: 'Adjust matched project',
      actionAdjustMatchedProjectDesc: 'Jump straight into the active project detail and tune presets or direct skills.',
      actionReviewOtherProjects: 'Review other projects',
      actionReviewOtherProjectsDesc: 'Compare tracked projects before making wider governance changes.',
      actionInspectGlobalSkills: 'Inspect global skills',
      actionInspectGlobalSkillsDesc: 'Check global enablement and project intersections in the skill directory.',
      actionReviewTrackedProjects: 'Review tracked projects',
      actionReviewTrackedProjectsDesc: 'Start with the project index to understand current activation across this setup.',
      actionGovernPresets: 'Govern presets',
      actionGovernPresetsDesc: 'Inspect reusable preset bundles before touching individual projects.',
      actionCheckGlobalBaseline: 'Check global baseline',
      actionCheckGlobalBaselineDesc: 'Review skills directory and default targets for the whole setup.',
      relationshipHeading: 'Influence chain',
      relationshipGlobalPresetsActive:
        '{{count}} global preset(s) currently shape shared defaults before project-level overrides.',
      relationshipGlobalPresetsEmpty: 'No global presets are shaping shared defaults right now.',
      relationshipProjects:
        '{{projects}} tracked project(s) currently carry {{count}} direct skill assignment(s).',
      relationshipRegistry:
        '{{presetCount}} preset definition(s) are available, while {{skillCount}} skill(s) are enabled globally.',
      configPayloadMustBeObject: 'Config update payload must be an object.',
      configPayloadHint: 'Send JSON like `{ "skillsDir": "...", "defaultTargets": [".agents"] }`.',
      skillsDirMustBeNonEmpty: 'skillsDir must be a non-empty string.',
      skillsDirHint: 'Enter an existing directory path for `skillsDir`.',
      skillsDirField: 'Enter an existing directory path.',
      defaultTargetsMustBeArray: 'defaultTargets must be a string array.',
      defaultTargetsHint: 'Use one or more of: {{targets}}',
      projectNotFound: 'Project {{projectId}} was not found in projects index.',
      projectNotFoundHint: 'Load projects from `GET /api/projects` and use a returned `projectId`.',
      projectStateMissing: 'Project state is missing for {{projectPath}}.',
      projectStateMissingHint: 'Re-enable a skill or preset in that project to recreate `.skm/state.json`.',
      presetNameRequired: 'Preset name is required.',
      presetNameHint: 'Use a non-empty preset name.',
      presetReadonly: 'This preset is readonly.',
      enableGlobalSkillPayload: 'Turn-on global skill payload must be an object.',
      enableGlobalSkillPayloadHint: 'Send JSON like `{ "skillNames": ["brainstorming"], "targets": [".agents"] }`.',
      disableGlobalSkillPayload: 'Turn-off global skill payload must be an object.',
      disableGlobalSkillPayloadHint: 'Send JSON like `{ "skillNames": ["brainstorming"] }`.',
      enableProjectSkillPayload: 'Turn-on skill payload must be an object.',
      enableProjectSkillPayloadHint: 'Send JSON like `{ "skillNames": ["brainstorming"], "targets": [".agents"] }`.',
      disableProjectSkillPayload: 'Turn-off skill payload must be an object.',
      disableProjectSkillPayloadHint: 'Send JSON like `{ "skillNames": ["brainstorming"] }`.',
      enablePresetPayload: 'Turn-on preset payload must be an object.',
      enablePresetPayloadHint: 'Send JSON like `{ "presetNames": ["frontend-basic"], "targets": [".agents"] }`.',
      disablePresetPayload: 'Turn-off preset payload must be an object.',
      disablePresetPayloadHint: 'Send JSON like `{ "presetNames": ["frontend-basic"] }`.',
      createPresetPayload: 'Create preset payload must be an object.',
      createPresetPayloadHint: 'Send JSON like `{ "name": "frontend", "skills": ["brainstorming"] }`.',
      updatePresetPayload: 'Update preset payload must be an object.',
      updatePresetPayloadHint: 'Send JSON like `{ "skills": ["brainstorming"] }`.',
      presetAlreadyExists: 'Preset {{name}} already exists.',
      presetAlreadyExistsHint: 'Choose a different name or update the existing preset.',
      presetReadonlyMutation: 'Preset {{name}} is a dynamic scope preset and cannot be modified.',
      presetReadonlyMutationHint:
        'Rename or remove the scope directory to change it, or create a different static preset name in `presets.yaml`.',
      presetNotFound: 'Preset {{name}} was not found.',
      presetNotFoundHint: 'Use `skm preset list` or `GET /api/presets` to inspect available presets.',
      presetSkillsRequired: 'Preset skills cannot be empty.',
      presetSkillsRequiredHint: 'Provide at least one skill name.',
      presetUnknownSkills: 'Preset references unknown skill(s): {{names}}.',
      presetUnknownSkillsHint: 'Run `skm skill list` and use only existing skill names in preset definitions.',
      presetNameFieldRequired: 'Preset name is required.',
      presetNameFieldConflict: 'Choose a different preset name.',
      stringArrayMustBe: '{{name}} must be a string array.',
      stringArrayHint: 'Provide `{{name}}` as a JSON string array.',
      stringArrayField: '{{name}} must be a list of strings.',
      skillsDirMissing: 'Skills directory does not exist: {{path}}.',
      skillsDirNotDirectory: 'Skills directory is not a directory: {{path}}.',
      skillsDirInvalidHint: 'Enter a path that exists and points to a directory.',
      directLabel: 'Direct',
      viaPresetLabel: 'Via Preset: {{name}}',
    },
    quickOpen: {
      openedInCode: 'Opened the project in VS Code.',
      openedWithSystem: 'Opened the project with the system default handler.',
      failed: 'Unable to open the project. code: {{codeError}}; default: {{defaultError}}',
    },
    time: {
      unknown: 'Unknown',
      justNow: 'just now',
      underMinuteFuture: 'in under a minute',
      minuteAgo: '{{count}}m ago',
      minuteIn: 'in {{count}}m',
      hourAgo: '{{count}}h ago',
      hourIn: 'in {{count}}h',
      yesterday: 'yesterday',
      tomorrow: 'tomorrow',
      dayAgo: '{{count}}d ago',
      dayIn: 'in {{count}}d',
    },
  },
};

function resolveMessage(locale: UiLocale, key: string): string | null {
  const segments = key.split('.');
  let current: UiTextValue | undefined = MESSAGES[locale];

  for (const segment of segments) {
    if (!current || typeof current === 'string') {
      return null;
    }
    current = current[segment];
  }

  return typeof current === 'string' ? current : null;
}

function interpolate(template: string, params?: Record<string, string | number>): string {
  if (!params) {
    return template;
  }

  return template.replace(/\{\{(\w+)\}\}/g, (_match, key: string) => {
    const value = params[key];
    return value === undefined ? '' : String(value);
  });
}

export function parseUiLocale(value: unknown): UiLocale | null {
  const candidate = Array.isArray(value) ? value[0] : value;
  return candidate === 'zh-CN' || candidate === 'en-US' ? candidate : null;
}

export function normalizeUiLocale(value: unknown, fallback: UiLocale = DEFAULT_UI_LOCALE): UiLocale {
  return parseUiLocale(value) ?? fallback;
}

export function translateUiText(
  locale: UiLocale,
  key: string,
  params?: Record<string, string | number>,
): string {
  const message = resolveMessage(locale, key) ?? resolveMessage(DEFAULT_UI_LOCALE, key) ?? key;
  return interpolate(message, params);
}

export function formatUiDateTime(locale: UiLocale, value?: string | null): string {
  if (!value) {
    return translateUiText(locale, 'time.unknown');
  }

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return String(value);
  }

  return new Intl.DateTimeFormat(locale, {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(date);
}

export function formatUiRelativeTime(locale: UiLocale, value?: string, now = Date.now()): string {
  if (!value) {
    return translateUiText(locale, 'time.unknown');
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return String(value);
  }

  const diffMs = now - parsed.getTime();
  const future = diffMs < 0;
  const absMs = Math.abs(diffMs);
  const minute = 60 * 1000;
  const hour = 60 * minute;
  const day = 24 * hour;

  if (absMs < minute) {
    return translateUiText(locale, future ? 'time.underMinuteFuture' : 'time.justNow');
  }

  if (absMs < hour) {
    const minutes = Math.round(absMs / minute);
    return translateUiText(locale, future ? 'time.minuteIn' : 'time.minuteAgo', { count: minutes });
  }

  if (absMs < day) {
    const hours = Math.round(absMs / hour);
    return translateUiText(locale, future ? 'time.hourIn' : 'time.hourAgo', { count: hours });
  }

  const days = Math.round(absMs / day);
  if (days === 1) {
    return translateUiText(locale, future ? 'time.tomorrow' : 'time.yesterday');
  }

  return translateUiText(locale, future ? 'time.dayIn' : 'time.dayAgo', { count: days });
}

export function sourceStateLabel(locale: UiLocale, source: 'static' | 'dynamic', readonly: boolean): string {
  if (readonly) {
    return translateUiText(locale, 'common.readonly');
  }
  return translateUiText(locale, source === 'dynamic' ? 'common.dynamic' : 'common.static');
}

export function formatResolvedSourceLabel(locale: UiLocale, presetName?: string): string {
  if (!presetName) {
    return translateUiText(locale, 'common.viaPreset');
  }
  return translateUiText(locale, 'facade.viaPresetLabel', { name: presetName });
}
